# Generated by Django 5.2.1 on 2025-06-17 14:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_businessdetails_delete_businesscoredetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
