# Generated by Django 5.2.1 on 2025-05-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_businessdetails_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='name2',
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/business_details/'),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
