# Generated by Django 5.2.1 on 2025-06-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_remove_businessdetails_name2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessDetails',
            new_name='BusinessModel',
        ),
    ]
