# Generated by Django 5.2.1 on 2025-06-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
