# Generated by Django 5.2.1 on 2025-06-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='delivery',
            name='Delivery_de_parcel__71ede4_idx',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery_city',
            new_name='delivery_town',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_postal_code',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_route',
            field=models.CharField(choices=[('Langata', 'Langata'), ('Ngong', 'Ngong'), ('Jogoo', 'Jogoo'), ('Mombasa', 'Mombasa'), ('Thika', 'Thika'), ('Waiyaki', 'Waiyaki'), ('Kiambu', 'Kiambu'), ('Limuru', 'Limuru'), ('Ardhwings_Kodek', 'Ardhwings Kodek'), ('Lower_Kabete', 'Lower Kabete'), ('Peponi', 'Peponi')], default=None, max_length=50),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['parcel_id', 'customer_name', 'customer_phone', 'delivery_town', 'delivery_address'], name='Delivery_de_parcel__af7403_idx'),
        ),
    ]
