# Generated by Django 5.2.1 on 2025-06-05 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
        ('Delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='customer_phone',
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='Customers.customer'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
