# Generated by Django 5.2.1 on 2025-06-07 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0002_delivery_delivery_cost'),
        ('Delivery', '0002_delivery_delivery_cost_and_more'),
    ]

    operations = [
    ]
