# Generated by Django 5.2.1 on 2025-06-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0002_remove_delivery_delivery_de_parcel__71ede4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_route',
            field=models.CharField(choices=[('Langata', 'Langata'), ('Ngong', 'Ngong'), ('Jogoo', 'Jogoo'), ('Mombasa', 'Mombasa'), ('Thika', 'Thika'), ('Waiyaki', 'Waiyaki'), ('Kiambu', 'Kiambu'), ('Limuru', 'Limuru'), ('Ardhwings_Kodek', 'Ardhwings Kodek'), ('Lower_Kabete', 'Lower Kabete'), ('Peponi', 'Peponi')], default='Thika', max_length=50),
        ),
    ]
