# Generated by Django 5.2.1 on 2025-06-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0003_merge_20250607_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
