# Generated by Django 5.2.1 on 2025-06-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0003_alter_delivery_delivery_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_route',
            field=models.CharField(blank=True, choices=[('Langata', 'Langata'), ('Ngong', 'Ngong'), ('Jogoo', 'Jogoo'), ('Mombasa', 'Mombasa'), ('Thika', 'Thika'), ('Waiyaki', 'Waiyaki'), ('Kiambu', 'Kiambu'), ('Limuru', 'Limuru'), ('Ardhwings_Kodek', 'Ardhwings Kodek'), ('Lower_Kabete', 'Lower Kabete'), ('Peponi', 'Peponi')], default='Thika', max_length=50, null=True),
        ),
    ]
