# Generated by Django 5.2.1 on 2025-06-15 13:34

import Delivery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0004_alter_delivery_delivery_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='parcel_id',
            field=models.CharField(default=Delivery.models.generate_parcel_id, editable=False, max_length=6, unique=True),
        ),
    ]
