# Generated by Django 5.2.1 on 2025-06-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0005_alter_delivery_parcel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['parcel_id', 'customer_name', 'customer_phone', 'delivery_city', 'delivery_address'], name='Delivery_de_parcel__71ede4_idx'),
        ),
    ]
